name: Deploy Tevkifat Module

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Tevkifat Modulunu Guncelle
        run: /home/prime/deploy_tevkifat.sh
